### ISSUE TITLE
Error on build when using node v9.11.2 (SyntaxError: Invalid regular expression /^.*?\((?<label>.*?)[,)]/: Invalid group from ow module)

### ISSUE THREAD

**Issue by didrip** [ykob/sketch-threejs#14]
This issue is for the record in case anyone encounters the same problem

`npm install && npm run start` =>

```
run start

> sketch-threejs.js@2.0.0 start /path/to/code/sketch-threejs
> npm run dev


> sketch-threejs.js@2.0.0 dev /path/to/sketch-threejs
> cross-env NODE_ENV=development gulp

SyntaxError: Invalid regular expression: /^.*?\((?<label>.*?)[,)]/: Invalid group
    at Object.<anonymous> (/path/to/node_modules/ow/dist/source/index.js:1:26679)
    at r /path/to/sketch-threejs/node_modules/ow/dist/source/index.js:1:186)
    at Object.module.exports.r /path/to/sketch-threejs/node_modules/ow/dist/source/index.js:1:11962)
    at r (/path/to/sketch-threejs/node_modules/ow/dist/source/index.js:1:186)
    at module.exports.Object.defineProperty.value (/path/to/sketch-threejs/node_modules/ow/dist/source/index.js:1:985)
    at Object.<anonymous> (/path/to/sketch-threejs/node_modules/ow/dist/source/index.js:1:994)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
```

builds fine on node v10.15.3

**Comment by ykob** [comment]
@didrip 
Thanks for making the issue. I will confirm it.

**Comment by ykob** [comment]
I've updated engines value on package.json.
https://github.com/ykob/sketch-threejs/blob/main/package.json#L15-L17

I intend to update it again when Node.js is updated.
